(use-modules (gnu home)
	     ((gnu packages xorg) #:select (xrdb xrandr xinit))
	     ((gnu packages xdisorg) #:select(redshift))
	     ((gnu packages suckless) #:select (slstatus dmenu))
	     ((gnu packages python) #:select (python))
	     ((guix gexp) #:select (gexp))
	     ((guix build-system copy) #:select (copy-build-system))
	     ((guix build-system trivial) #:select (trivial-build-system))
	     ((guix transformations) #:select (options->transformation))
	     ((guix packages) #:select (package origin base32 package-version package-source))
	     ((guix download) #:select (url-fetch))
	     ((guix git-download) #:select(git-fetch git-reference git-file-name))
	     ((gnu packages suckless) #:select (dwm slock dmenu))
	     (gnu home services)
	     ((gnu home services guix) #:select (home-channels-service-type))
	     ((guix channels) #:select (channel make-channel-introduction openpgp-fingerprint %default-channels))
	     ((gnu services syncthing) #:select (syncthing-service-type syncthing-configuration))
             (gnu packages)
	     ((guix packages) #:select (modify-inputs package-inputs))
             (gnu services)
             (guix gexp)
             (gnu home services shells)
	     (gnu home services xdg))


(define version "6.4")
(origin
             (method git-fetch)
             (uri (git-reference (url "https://git.suckless.org/dwm")
                                 (commit version)))
	     (file-name (git-file-name "dwm" version))
             (sha256 (base32 "025x6rbw61c8l3dsdlkb6wawp8236wy0314jlsxi1jyxnfbml4ds"))
	     (patches (list
		       (origin (method url-fetch)
			(uri "https://dwm.suckless.org/patches/pango/dwm-pango-20230520-e81f17d.diff")
			(sha256 (base32 "0921063c631y770xnfn7dxdb6g3b579r0x3a369amcymf6qb755n")))
		       ;(origin (method url-fetch)
		       ; (uri "https://dwm.suckless.org/patches/hide_vacant_tags/dwm-hide_vacant_tags-6.4.diff")
		       ; (sha256 (base32 "1avzp0mg7f77ifzg6h05f8z6fpx6wly8c018sxn2l7vw8avfj42p")))
		       (origin (method url-fetch)
	                (uri "https://dwm.suckless.org/patches/holdbar/dwm-holdbar-modkey-pertag-nobar-6.2.diff")
	                (sha256 (base32 "0hymhhp2w3rx3006dxwblf7lh4yq3bi958r0qj1x4aszkvdzx1f6")))
		       (origin (method url-fetch)
		        (uri "https://dwm.suckless.org/patches/autostarttags/dwm-autostarttags-6.4.diff")
		        (sha256 (base32 "0rc75hip9kayh62mwhrfp0jjrf1z1l0617mviy5qaqyvxi4g994z")))
		       (origin (method url-fetch)
	                (uri "https://dwm.suckless.org/patches/actualfullscreen/dwm-actualfullscreen-20211013-cb3f58a.diff")
	                (sha256 (base32 "0882k8w6651c18ina0245b558f1bvqydcycw07lp711hpbg7f9gv")))
		       
		       ;; and finally apply the local dwm patch which is updated by the guixman command
		       ;; the command relies on having the dwm source code with git set to the result of the above patches to work correctly
		       ;; and there is not really a good way to store that as I want the diff to be saved as the cononical edits but need a place to make those edits to generate the diff.
		       ;;(local-file "./dwm_personal.diff")
		       )))
